import {
  Scale,
  FileText,
  Calculator,
  Tags,
  Brain,
  Users,
  Puzzle,
  BarChart3,
  History,
  Bug,
  Code,
  Database,
  SlidersHorizontal,
  LineChart,
  Server,
  Receipt,
  FileCheck,
  FolderSearch,
  Map,
} from 'lucide-react'
import type { SystemCardConfig, AdminCardConfig } from './types'

/** Cards dos 8 sistemas no dashboard (mesma ordem do legado) */
export const systemCards: SystemCardConfig[] = [
  {
    to: '/assistencia',
    icon: Scale,
    title: 'Assistência Judiciária',
    description: 'Consulta de processos judiciais no TJ-MS com análise automática por IA.',
    color: 'primary',
  },
  {
    to: '/matriculas',
    icon: Map,
    title: 'Matrículas Confrontantes',
    description: 'Análise documental de matrículas imobiliárias com IA visual.',
    color: 'green',
  },
  {
    to: '/gerador-pecas',
    icon: FileText,
    title: 'Gerador de Peças',
    description: 'Geração automatizada de contestações, pareceres e recursos.',
    color: 'purple',
  },
  {
    to: '/pedido-calculo',
    icon: Calculator,
    title: 'Pedido de Cálculo',
    description: 'Geração de pedido de cálculo para cumprimento de sentença.',
    color: 'amber',
  },
  {
    to: '/prestacao-contas',
    icon: Receipt,
    title: 'Prestação de Contas',
    description: 'Análise de prestação de contas em processos de medicamentos.',
    color: 'teal',
  },
  {
    to: '/relatorio-cumprimento',
    icon: FileCheck,
    title: 'Relatório de Cumprimento',
    description: 'Geração de relatório inicial para cumprimento de sentença.',
    color: 'emerald',
  },
  {
    to: '/extrator-autos',
    icon: FolderSearch,
    title: 'Extrator de Autos',
    description: 'Download e classificação de documentos processuais via TJ-MS.',
    color: 'sky',
    adminOnly: true,
  },
  {
    to: '/classificador',
    icon: Tags,
    title: 'Classificador de Documentos',
    description: 'Classificação automática de documentos jurídicos com IA.',
    color: 'indigo',
    adminOnly: true,
  },
  {
    to: '/bert-training',
    icon: Brain,
    title: 'BERT Training',
    description: 'Treinamento de classificadores de texto com modelos BERT.',
    color: 'rose',
    adminOnly: true,
  },
]

/** Cards do painel administrativo (12 cards, mesma ordem do legado) */
export const adminCards: AdminCardConfig[] = [
  {
    to: '/admin/users',
    icon: Users,
    title: 'Usuários',
    subtitle: 'Gerenciar acessos',
    color: 'gray',
  },
  {
    to: '/admin/prompts',
    icon: Brain,
    title: 'Prompts de IA',
    subtitle: 'Configurar prompts',
    color: 'purple',
  },
  {
    to: '/admin/prompts-modulos',
    icon: Puzzle,
    title: 'Prompts Modulares',
    subtitle: 'Editar e versionar prompts',
    color: 'orange',
  },
  {
    to: '/admin/feedbacks',
    icon: BarChart3,
    title: 'Dashboard Feedbacks',
    subtitle: 'Avaliar qualidade da IA',
    color: 'blue',
  },
  {
    to: '/admin/historico-gerador',
    icon: History,
    title: 'Histórico Gerações',
    subtitle: 'Prompts e resultados',
    color: 'indigo',
  },
  {
    to: '/admin/historico-pedido-calculo',
    icon: Bug,
    title: 'Debug Pedido Cálculo',
    subtitle: 'Logs de chamadas IA',
    color: 'amber',
  },
  {
    to: '/admin/historico-prestacao-contas',
    icon: Bug,
    title: 'Debug Prestação Contas',
    subtitle: 'Logs de chamadas IA',
    color: 'teal',
  },
  {
    to: '/admin/categorias-json',
    icon: Code,
    title: 'Formatos JSON',
    subtitle: 'Categorias de resumo',
    color: 'green',
  },
  {
    to: '/admin/variaveis',
    icon: Database,
    title: 'Variáveis de Extração',
    subtitle: 'Perguntas e variáveis IA',
    color: 'cyan',
  },
  {
    to: '/admin/modulos-tipo-peca',
    icon: SlidersHorizontal,
    title: 'Tipos de Peça',
    subtitle: 'Categorias por tipo',
    color: 'purple',
  },
  {
    to: '/admin/performance',
    icon: LineChart,
    title: 'Logs de Performance',
    subtitle: 'Latência e diagnósticos',
    color: 'rose',
  },
  {
    to: '/admin/tjms-docs',
    icon: Server,
    title: 'Integração TJ-MS',
    subtitle: 'Docs e sincronização',
    color: 'sky',
  },
]
